### ISSUE TITLE
Not able to make the lib work with SvelteKit

### ISSUE THREAD

**Issue by Nderim1** [tsparticles/svelte#12]
Hi, I have a SvelteKit app and I am trying to include the particle lib to my project by following [the svelte docs](https://github.com/tsparticles/svelte).

I am experiencing this error:
![image](https://github.com/tsparticles/svelte/assets/15191094/04b790f8-f671-4363-bd7b-32bca37622ee)

Things I did:
- installed the library as per https://github.com/tsparticles/svelte
- tried to included it in one of my components
- also tried setting the preprocessor from vite to svelte-preprocessor but did not change much

Would appreciate any help. Let me know if you need more info.

**Comment by Shrumpf** [comment]
Same here after updating from 2.9.3 to 2.10.1.

**Comment by matteobruni** [comment]
> Same here after updating from 2.9.3 to 2.10.1.
If you need please open a new issue with a reproducible sample or steps to reproduce the problem
