### ISSUE TITLE
Unable to have particles appear in Svelte Website

### ISSUE THREAD

**Issue by ABansal11** [tsparticles/svelte#25]
@matteobruni  I am trying to implement the particles in a Svelte website. I have simply used the code from this repo in the app.svelte file. However, I have not been able to have the particles appear on the localhost server. 

I am relatively new to this, so  it may be an easy fix. I unfortunately could not find anything to make it work after many attempts. 

My JS code is as follows:

```
  import Particles from "svelte-particles";
  import { loadSlim } from "tsparticles-slim"; 

  let particlesConfig = {
        particles: {
            color: {
                value: "#000",
            },
            links: {
                enable: true,
                color: "#000",
            },
            move: {
                enable: true,
            },
            number: {
                value: 100,
            },
            shape: {
              type: 'circle'
            },
            size: {
              value: {
                min: 1,
                max: 5
          
              }
            }
        },
        fullScreen: {
          enable: true,
          zIndex: 0
        }
    };
    let onParticlesLoaded = event => {
        const particlesContainer = event.detail.particles;
    };

    let particlesInit = async engine => {
        await loadSlim(engine);
    };
```

I place the HTML code as so: 
```
<main>
    <nav>
    </nav>
    <Particles
         id="tsparticles"
         class="foo bar"
         style=""
         options={particlesConfig}
         on:particlesLoaded={onParticlesLoaded}
         particlesInit={particlesInit}
    />
</main>
```

**Comment by matteobruni** [comment]
Are you using SSR? Try this: https://github.com/tsparticles/svelte#ssr
Are you using SvelteKit? Try this: https://github.com/tsparticles/svelte#sveltekit

If none of these, please provide a repo using [CodeSandbox](https://codesandbox.io/)

**Comment by ABansal11** [comment]
I got the following error after restarting and trying to open the website in live view again: 
`[!](plugin svelte) ParseError: Unexpected token  
node_modules\svelte-particles\src\Particles.svelte
3: <script lang="ts">
4:     import { afterUpdate, createEventDispatcher, onDestroy } from "svelte";
5:     import type { ISourceOptions } from "tsparticles-engine";
                   ^
6:     import { tsParticles } from "tsparticles-engine";
7:
ParseError: Unexpected token
    at error (C:\svelte-tut\CHSwebdev.io\node_modules\svelte\src\compiler\utils\error.ts:25:16)
    at Parser$1.error (C:\svelte-tut\CHSwebdev.io\node_modules\svelte\src\compiler\parse\index.ts:105:3)
    at Parser$1.acorn_error (C:\svelte-tut\CHSwebdev.io\node_modules\svelte\src\compiler\parse\index.ts:98:8)
    at Object.read_script [as read] (C:\svelte-tut\CHSwebdev.io\node_modules\svelte\src\compiler\parse\read\script.ts:43:10)
    at tag (C:\svelte-tut\CHSwebdev.io\node_modules\svelte\src\compiler\parse\state\tag.ts:211:27)
    at new Parser$1 (C:\svelte-tut\CHSwebdev.io\node_modules\svelte\src\compiler\parse\index.ts:57:12)
    at parse (C:\svelte-tut\CHSwebdev.io\node_modules\svelte\src\compiler\parse\index.ts:230:17)
    at compile (C:\svelte-tut\CHSwebdev.io\node_modules\svelte\src\compiler\compile\index.ts:122:14)
    at Object.transform (C:\svelte-tut\CHSwebdev.io\node_modules\rollup-plugin-svelte\index.js:111:21)
    at C:\svelte-tut\CHSwebdev.io\node_modules\rollup\dist\shared\rollup.js:22795:37`

**Comment by matteobruni** [comment]
Ok it's a TypeScript error, try this: https://github.com/tsparticles/svelte#typescript-errors

**Comment by ABansal11** [comment]
@matteobruni Thanks for help so far. I tried the TypeScript fix, but did not work. I believe reason for this is that the mentioned steps are for SvelteKit projects only.

**Comment by matteobruni** [comment]
I've tried using the instructions from the Svelte Website, using Vite and not SvelteKit, and everything worked as expected.

I've run this commands: https://svelte.dev/docs/introduction#start-a-new-project-alternatives-to-sveltekit

And installed `svelte-particles` and `tsparticles`, added the code from the readme of this repository using `tsparticles` instead of `tsparticles-slim` (but it doesn't matter) and it worked.

I need more details on your configuration. I think something is missing on your side.

**Comment by ABansal11** [comment]
As you previously requested, I have put the code into a repo using CodeSandbox

[Repo Link](https://codesandbox.io/p/github/ABansal11/CHSWebDev/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clkznc63u000h356mnr6ix9ve%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clkznc63u000c356mb5nolgpa%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clkznc63u000g356m7f9c7pdv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clkznc63u000e356mjc3dnc0p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clkznc63u000c356mb5nolgpa%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clkznc63u000b356m4ox6wxit%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clkznc63u000c356mb5nolgpa%2522%252C%2522activeTabId%2522%253A%2522clkznc63u000b356m4ox6wxit%2522%257D%252C%2522clkznc63u000e356mjc3dnc0p%2522%253A%257B%2522id%2522%253A%2522clkznc63u000e356mjc3dnc0p%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clkznc63u000g356m7f9c7pdv%2522%253A%257B%2522id%2522%253A%2522clkznc63u000g356m7f9c7pdv%2522%252C%2522activeTabId%2522%253A%2522clkzncd1a00p6356mm5oouq4f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clkznc63u000f356moqvo731b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clkznc5dt000vhhd65jq18m7p%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clkzncd1a00p6356mm5oouq4f%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by matteobruni** [comment]
> As you previously requested, I have put the code into a repo using CodeSandbox. I hope that can help.
> 
> [Repo Link](https://codesandbox.io/p/github/ABansal11/CHSWebDev/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clkznc63u000h356mnr6ix9ve%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clkznc63u000c356mb5nolgpa%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clkznc63u000g356m7f9c7pdv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clkznc63u000e356mjc3dnc0p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clkznc63u000c356mb5nolgpa%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clkznc63u000b356m4ox6wxit%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clkznc63u000c356mb5nolgpa%2522%252C%2522activeTabId%2522%253A%2522clkznc63u000b356m4ox6wxit%2522%257D%252C%2522clkznc63u000e356mjc3dnc0p%2522%253A%257B%2522id%2522%253A%2522clkznc63u000e356mjc3dnc0p%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clkznc63u000g356m7f9c7pdv%2522%253A%257B%2522id%2522%253A%2522clkznc63u000g356m7f9c7pdv%2522%252C%2522activeTabId%2522%253A%2522clkzncd1a00p6356mm5oouq4f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clkznc63u000f356moqvo731b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clkznc5dt000vhhd65jq18m7p%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clkzncd1a00p6356mm5oouq4f%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Project not found

**Comment by ABansal11** [comment]
Please try this: 

[Repo link](https://codesandbox.io/embed/github/ABansal11/CHSWebDev/tree/main/?fontsize=14&hidenavigation=1&theme=dark)

**Comment by matteobruni** [comment]
Ok there’s a section in the svelte website for that: https://svelte.dev/docs/typescript#setup-other-build-tools

try this and let me know

**Comment by ABansal11** [comment]
Yes thanks it worked.
