### ISSUE TITLE
javaScript documentation please💔😕

### ISSUE THREAD

**Issue by moonhuntercode** [tsparticles/svelte#57]
a documentation for only javaScript devs please , for any what want a project with just javaScript

**Comment by matteobruni** [comment]
The readme is not using TypeScript, what's the problem?

**Comment by moonhuntercode** [comment]
I'm trying to use Svelte + vite.js and um.. with just javaScript and emm I had a hard time applying it at first, but using this example I was able to apply it
https://github.com/moonhuntercode/svelte-examples
